name: incloud

on:
#    workflow_dispatch: 推送测试选择，完成后使用如下
    workflow_dispatch:
      inputs:
        searchDomain:
          description: "Please enter the domain name to be scanned"
          required: true
          default: "csleasing.com.cn"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev 
           
        

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
          go get -v github.com/projectdiscovery/dnsx/cmd/dnsx
          go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu
          go get -v github.com/projectdiscovery/httpx/cmd/httpx
          go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
          go get -v github.com/projectdiscovery/mapcidr/cmd/mapcidr
          go get -u github.com/ffuf/ffuf
        shell: bash


      - name: Running SubFinder for passive DNS enumeration
        run: |
          echo "${{ env.searchDomain }}" > input/domains.txt
          cat input/domains.txt
          subfinder -dL input/domains.txt -config config/subfinder-config.yaml -o output/passive_subdomains.txt
        shell: bash

      - name: Running dnsx for valid DNS filtering 
        run: |
          dnsx -l output/passive_subdomains.txt -t 50 | tee output/active_subdomains.txt
        shell: bash

      - name: Running naabu to check top 1000 ports
        run: |
          naabu -iL output/active_subdomains.txt  -rate 10000 -top-ports 1000 | tee output/active_ports.txt
        shell: bash


      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output/active_ports.txt -title
          httpx -l output/active_ports.txt | tee output/active_urls.txt
        shell: bash
      - name: Running dirscan 
        run: |
          wget https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
          mkdir dirout
          set +e ;time for i in $(cat output/active_urls.txt );do ffuf -w dicc.txt -u $i/FUZZ -t 200 -mc 200 -ac -recursion -v -of csv -o dirout/`date +%Y%m%d%H%M%S`.csv; done
          cat dirout/*.csv >> output/dirout.csv
        shell: bash
          
      - name: Runing Webcrack
        run: |
          wget https://github.com/yzddmr6/WebCrack/archive/refs/heads/master.zip
          unzip master.zip
          cd WebCrack-master
          pip3 install -r requirements.txt
          cat ../output/dirout.csv | awk -F "," '{print $2}' | sed 's/url//g' | sed '/^\s*$/d' >> weburl.txt
          echo weburl.txt | python3 webcrack.py >> webcrack.txt
          cp webcrack.txt ../output/webcrack.txt
        shell: bash  

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
          tar -czf ${{ env.searchDomain }}-attachments.tar.gz output
          ls -la
          echo "扫描完成，这里是附件" > result.html
        shell: bash

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.com
          server_port: 465
          #username: ${{ secrets.MAIL_USERNAME }}
          #password: ${{ secrets.MAIL_PASSWORD }}
          username: ${{secrets.SENTRY_MAIL_USERNAME}}
          password: ${{secrets.SENTRY_MAIL_PASSWORD}}
          subject: "您的订阅信息"
          html_body: file://result.html
          to: bin4xin.sentrylab@qq.com
          #cc: chihou.pro@gmail.com
          #from: 哨兵 -  ${{ env.REPORT_COMMIT }}
          from: 哨兵 - 望远镜
          content_type: text/html
          attachments: ${{ env.searchDomain }}-attachments.tar.gz
#      - name: Create local changes
#        run: |
#          git add output/active_ports.txt
#          git add output/active_urls.txt
#          git add output/dirout.csv
#          git add output/webcrack.txt
#
#      - name: Commit results to Github
#        run: |
#          git config --local user.email "admin@inbug.org"
#          git config --global user.name "inbug-team"
#          git commit -m "InCloud Report" -a --allow-empty
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
